
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456

#  data:
#    redis:
#      host: localhost
#      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#server:
#  port: 80
#server:
#  address: 0.0.0.0
#  port: 443
#  ssl:
#    key-alias: pursuenova.club
#    key-store-password: ks3uu2b7b192tq8
#    key-store-type: PKCS12
#    key-store: classpath:pursuenova.club.pfx